name: Build napotd

on: [push]

jobs:
  Build-And-Push:
    runs-on: docker
#    container:
#      image: docker:dind
#      privileged: true
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: gitea.area-51-x.com
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          registry: gitea.area-51-x.com
          push: true
          tags: deltreey/napotd:latest, deltreey/napotd:${{gitea.ref_name}}
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.DOCKER_PASSWORD }}
